name: CI

on:
    push:
        branches: [ main, issue-* ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        environment:
          name: environment
        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Install dependencies
              run: |
                uv sync --frozen

            # Create a .env from GitHub secrets (keeps sensitive values out of repo)
            - name: Create .env from secrets
              run: |
                echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
                echo "TABLE=${{ secrets.TABLE }}" >> .env

            # Install pylint into the project environment so imports resolve
            - name: Install pylint
              run: |
                uv run python -m pip install --upgrade pip pylint

            # Run pylint in the project environment
            - name: Run pylint
              run: |
                uv run pylint src
