name: CI

on:
    push:
        branches: [ main, issue-* ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        environment:
          name: environment
        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Install dependencies
              run: |
                uv sync --frozen

            # Create a .env from GitHub secrets (quoted values, safe for special chars)
            - name: Create .env from secrets
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL }}
                TABLE: ${{ secrets.TABLE }}
              run: |
                {
                  printf 'DATABASE_URL="%s"\n' "$DATABASE_URL"
                  printf 'TABLE="%s"\n' "$TABLE"
                } > .env

            # Install pylint into the project environment
            - name: Install pylint
              run: |
                uv pip install --quiet pylint

            # Run pylint in the project environment
            - name: Run pylint
              run: |
                uv run pylint src
